In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
a[2]

3

# Why used numpy over list
1. less memory
2. fast
3. convinient

In [4]:
import sys

#list
l = range(1000)
print(sys.getsizeof(5)*len(l))

#numpy array  
array = np.array(1000)
print(array.size*array.itemsize)

28000
8


In [6]:
import time
SIZE = 100000000

# python list
start = time.time()
l1 = range(SIZE)
l2 = range(SIZE)
l3 = [(x+y) for x,y in zip(l1,l2)]
print(f" Python list time took : {(time.time()-start)*1000}")

# numpy array
start = time.time()
a1 = np.arange(SIZE)
a2 = np.arange(SIZE)
a3 = a1 + a2
print(f" Numpy array time took : {(time.time()-start)*1000}")

 Python list time took : 9864.86291885376
 Numpy array time took : 1317.5218105316162


In [7]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

a1 + a2

array([5, 7, 9])

In [9]:
a2 - a1

array([3, 3, 3])

In [10]:
a1 * a2

array([ 4, 10, 18])

In [11]:
a1 / a2

array([0.25, 0.4 , 0.5 ])