# numpy operations
1. ndim
2. itemsize
3. dtype
        i - integer
        b - boolean
        u - unsigned integer
        f - float
        c - complex float
        m - timedelta
        M - datetime
        O - object
        S - string
        U - unicode string
        V - fixed chunk of memory for other type ( void )
4. size
5. shape
6. zeros
7. ones
8. arange
9. linspace
10. reshape
11. reval
12. min
13. max
14. sum
    sum(axis)
15. std
16. sqrt




In [5]:
import numpy as np
a = np.array([1,2,3])
print(a.ndim)

a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)

1
2


In [6]:
a.itemsize

8

In [8]:
a = np.array([[1,2,3],[4,5,6]], dtype = "f")
a.dtype

dtype('float32')

In [9]:
a.size

6

In [10]:
a.shape

(2, 3)

In [11]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [14]:
np.arange(1,7,2)

array([1, 3, 5])

In [18]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
a.reshape(3,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)

In [20]:
a.ravel()

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [21]:
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [22]:
a.min()

1.0

In [23]:
a.max()

6.0

In [24]:
a.sum(axis = 0)

array([5., 7., 9.], dtype=float32)

In [25]:
np.sqrt(a)

array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898]], dtype=float32)

In [26]:
np.std(a)

1.7078252