In [1]:
import numpy as np
n = np.array([1,2,3,4])
n[0:3]

array([1, 2, 3])

In [2]:
n[-2]

3

In [3]:
n = np.array([[1,2,3,4],[6,7,8,9]])
n[0,2]

3

In [4]:
n[0:2,2]

array([3, 8])

In [5]:
n[-1]

array([6, 7, 8, 9])

In [6]:
n[-1,0:2]

array([6, 7])

In [7]:
n[:,2:4]

array([[3, 4],
       [8, 9]])

In [8]:
for i in n:
    print(i)

[1 2 3 4]
[6 7 8 9]


In [9]:
for i in n.flat:
    print(i)

1
2
3
4
6
7
8
9


In [10]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

In [11]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.hstack((a,b))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [22]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [23]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [24]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [25]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [28]:
a[b] = -1

In [29]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])