# Numpy tutorial: iterate numpy array using nditer


In [1]:
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Using normal for loop iteration

In [2]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


## For loop with flatten

In [3]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


# nditer

## C style ordering

In [4]:
for x in np.nditer(a, order = "C"):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


## Fortan style ordering

In [5]:
for x in np.nditer(a, order = "F"):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


## external_loop

In [6]:
for x in np.nditer(a, flags=['external_loop'],order='F'):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


## Modify array values while iterating

In [7]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

## Iterate two broadcastable arrays concurrently

In [8]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [9]:
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
